# Disclaimer: this is a list of profanity, offensive and similar low quality
# words used as a dictionary configuration for social interactions. Repository's
# code of conduct specifically suggest to be nice and respectful to others when
# interacting online with other people. For less offensive approach they are
# transformed with ROT13 encoding.
# They are not targeted at anyone in particular.
# Format: [ROT 13 string, points]
offensive_words:
    - ['lbh vqvbg', -20]
    - ['shpx lbh', -20]
    - ['shpx h', -20]
    - ['shpx', -20]
    - ['tb shpx lbhefrys', -20]
    - ['lbh''er na vqvbg', -20]
    - ['lbh ner na vqvbg', -20]
    - ['lbhe vqvbg', -20]
    - ['lbh ner qhzo', -20]
    - ['lbh''er qhzo', -20]
    - ['tb gb uryy', -20]
    - ['fgbc orvat ynml', -20]
    - ['qba''g or ynml', -20]
    - ['fuvg', -10]
    - ['nffubyr', -20]
    - ['zbgure s*pxre', -20]
    - ['Qbag or fb cngurgvp', -20]
    - ['lbh vqvbgf', -20]
    - ['vtabenag nff', -20]
    - ['ur frrzf gb or na vqvbg', -20]
